#!/usr/bin/env python3
"""Generate netfields.py from the NetFields.cpp of the reference implementation.

    py source/py/gen_netfields.py <pfad/zu/NetFields.cpp> [-o source/py/netfields.py]

Typing the tables out by hand would be error prone - every field sits at a
fixed position in the bit stream, and one transposition shifts everything
after it.
Quelle: https://github.com/Iswenzz/CoD4-DM1 (src/Crypt/NetFields.cpp)
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

TABLE = re.compile(r"netField_t NetFields::(\w+)\[\w+\]\s*=\s*\{(.*?)\n\t\};", re.S)
ENTRY = re.compile(r"\{\s*\w+\(([^)]*)\)\s*,\s*(-?\d+)\s*,\s*(\d+)\s*\}")
LIST = re.compile(r"netFieldList_t NetFields::List\[\w+\]\s*=\s*\{(.*?)\n\t\};", re.S)
LIST_ENTRY = re.compile(r"NETFE\((\w+)\)")


def snake(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).upper()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("source", type=Path)
    ap.add_argument("-o", "--out", type=Path, default=Path(__file__).with_name("netfields.py"))
    args = ap.parse_args()

    src = args.source.read_text(encoding="utf-8", errors="replace")
    tables: dict[str, list[tuple[str, int, int]]] = {}
    for name, body in TABLE.findall(src):
        fields = [(f.strip(), int(bits), int(hint)) for f, bits, hint in ENTRY.findall(body)]
        if not fields:
            raise SystemExit(f"could not read table {name}")
        tables[name] = fields

    m = LIST.search(src)
    if not m:
        raise SystemExit("NetFields::List not found")
    order = LIST_ENTRY.findall(m.group(1))

    lines = [
        '"""Net field tables for CoD4 delta entities.',
        "",
        "Generated by gen_netfields.py from the NetFields.cpp of",
        "https://github.com/Iswenzz/CoD4-DM1 - nicht von Hand aendern.",
        "",
        "Jeder Eintrag ist (name, bits, changeHints). bits == 0 bedeutet Float,",
        "negative Werte sind Sonderkodierungen (siehe read_delta_field in dm1.py).",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]
    for name, fields in tables.items():
        lines.append(f"{snake(name)} = (")
        for f, bits, hint in fields:
            lines.append(f'    ("{f}", {bits}, {hint}),')
        lines.append(")")
        lines.append("")
    lines.append("#: eType -> Feldtabelle (Index >= len-1 wird geklemmt)")
    lines.append("LIST = (")
    for name in order:
        lines.append(f"    {snake(name)},")
    lines.append(")")
    lines.append("")

    args.out.write_text("\n".join(lines), encoding="utf-8", newline="\n")

    # the same table for the web version
    js = ["/*! netfields.js - generated by source/py/gen_netfields.py from the NetFields.cpp",
          " *  of https://github.com/Iswenzz/CoD4-DM1 - do not edit by hand.",
          " *  Each entry is [name, bits, changeHints]; bits 0 = float, negative values are",
          " *  special encodings (see readDeltaField in snapshot.js). */",
          "(function (root) {", '"use strict";', "const NF = {};"]
    for name, fields in tables.items():
        js.append(f"NF.{snake(name)} = [")
        js.append(",\n".join(f'  ["{f}",{bits},{hint}]' for f, bits, hint in fields))
        js.append("];")
    js.append("NF.LIST = [" + ",".join("NF." + snake(n) for n in order) + "];")
    js.append("root.DM1_NETFIELDS = NF;")
    js.append("})(typeof globalThis !== \"undefined\" ? globalThis : this);")
    # The web version lives in source/js - the path hangs off this file, not
    # off --out, otherwise a different target would write into nowhere.
    js_out = Path(__file__).resolve().parents[1] / "js" / "netfields.js"
    txt = "\n".join(js)
    js_out.write_text(txt, encoding="ascii", newline="\n")
    print(f"{js_out}: {len(txt)} Bytes")
    print(f"{args.out}: {len(tables)} tables, "
          f"{sum(len(v) for v in tables.values())} Felder, List mit {len(order)} Eintraegen")
    for name, fields in tables.items():
        print(f"  {name:<32} {len(fields):>3} fields")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
