#!/usr/bin/env python3
"""Generate the static decoder tables of the web viewer (js/parser/tables.js).

    py tools/gen_js_tables.py

Source: the verified tables of the Python package (``_huffman_table.py``,
``_netfields.py``), so that the Python extractor and the JavaScript viewer
decode with exactly the same data.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(HERE))

from cod4demo import _netfields as NF          # noqa: E402
from cod4demo._huffman_table import CODES, FINGERPRINT  # noqa: E402

OUT = HERE.parent / "js" / "parser" / "tables.js"


def compact(obj) -> str:
    return json.dumps(obj, separators=(",", ":"))


def main() -> int:
    huff = [list(CODES[s]) for s in range(256)]
    ent_tables = []
    for t in NF.ENTITY_TABLES:
        ent_tables.append([[f[0], f[1], f[2], f[3], f[4]] for f in t])

    def plain(table):
        return [[f[0], f[1], f[2], f[3]] for f in table]

    lines = [
        "/* Static decoder tables - GENERATED by python/tools/gen_js_tables.py, do not edit.",
        " * Huffman codes of the CoD4 message compression and the net field tables",
        " * (name, bits, changeHints, kind[, slot]); see python/README.md section 5. */",
        "C4.define('tables', function (C4) {",
        "  'use strict';",
        "  C4.tables = {",
        f"    HUFFMAN_FINGERPRINT: {json.dumps(FINGERPRINT)},",
        f"    HUFFMAN_CODES: {compact(huff)},",
        f"    ENTITY_WORDS: {NF.ENTITY_WORDS},",
        f"    ENTITY_TABLES: {compact(ent_tables)},",
        f"    ENTITY_TABLE_NAMES: {compact(list(NF.ENTITY_TABLE_NAMES))},",
        f"    PLAYER_STATE_FIELDS: {compact(plain(NF.PLAYER_STATE_FIELDS))},",
        f"    CLIENT_STATE_FIELDS: {compact(plain(NF.CLIENT_STATE_FIELDS))},",
        f"    HUD_ELEM_FIELDS: {compact(plain(NF.HUD_ELEM_FIELDS))},",
        f"    OBJECTIVE_FIELDS: {compact(plain(NF.OBJECTIVE_FIELDS))}",
        "  };",
        "});",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="ascii", newline="\n")
    print(f"{OUT}: {OUT.stat().st_size} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
